/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jlab_coda_et_EtJniAccess */

#ifndef _Included_org_jlab_coda_et_EtJniAccess
#define _Included_org_jlab_coda_et_EtJniAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    openLocalEtSystem
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_openLocalEtSystem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    closeLocalEtSystem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_closeLocalEtSystem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    putEvents
 * Signature: (JI[Lorg/jlab/coda/et/EtEventImpl;I)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_putEvents
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    dumpEvents
 * Signature: (JI[Lorg/jlab/coda/et/EtEventImpl;I)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_dumpEvents
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    getEvents
 * Signature: (JIIIII)[Lorg/jlab/coda/et/EtEventImpl;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jlab_coda_et_EtJniAccess_getEvents
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    newEvents
 * Signature: (JIIIIIII)[Lorg/jlab/coda/et/EtEventImpl;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jlab_coda_et_EtJniAccess_newEvents
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
