# scons build file for evio
Import('env', 'libInstallDir', 'incInstallDir', 'archIncInstallDir', 'debugSuffix')

# Headers to install
headerList = Glob('*.h',  strings=True)

# Files to compile
fileList = Glob('*.c',  strings=True)

env.AppendUnique(CPPPATH = ['.'])
evioLib = env.SharedLibrary(target = 'evio'+debugSuffix, source = fileList)

if 'install' in COMMAND_LINE_TARGETS:
    env.Alias("install", env.Install(target = [incInstallDir, archIncInstallDir], source = headerList))
    env.Alias("install", env.Install(target = libInstallDir, source = evioLib))
